# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='favourites',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
