# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='avatar',
            field=models.ImageField(default='', upload_to='ong/avatar/'),
            preserve_default=False,
        ),
    ]
