# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20171023_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='color',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Macho'), (2, 'Hembra')], null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='wounded',
            field=models.NullBooleanField(choices=[(True, 'Sí'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='complaints/'),
        ),
    ]
